"""Inital migration

Revision ID: 598b101b2787
Revises: 
Create Date: 2024-11-22 17:26:06.861350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598b101b2787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('topics', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('sources', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('regions', sa.ARRAY(sa.String()), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('regions')
        batch_op.drop_column('sources')
        batch_op.drop_column('topics')
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
