"""Add topics field to Document model

Revision ID: 881c4812a525
Revises: 598b101b2787
Create Date: 2024-11-22 17:42:42.966178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881c4812a525'
down_revision = '598b101b2787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('topics')

    # ### end Alembic commands ###
