"""Update author to Document

Revision ID: f4246c6712aa
Revises: 6ded3324e307
Create Date: 2024-11-25 16:26:36.155785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4246c6712aa'
down_revision = '6ded3324e307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
